<?php

namespace Sikelan\Tests\trader_test;

use App\Commands\TraderMakeStrategyCommand;
use PHPUnit\Framework\TestCase;
use Sikelan\Command\CommandManager;
use Sikelan\Command\CommandRunner;

/**
 * trader:make-strategy 命令测试。
 *
 * 所有会写文件 / 改 config 的用例都在 sys_get_temp_dir 下的临时目录操作，
 * 绝不触碰项目真实的 app/ 或 config/trader.php。
 */
class TraderMakeStrategyCommandTest extends TestCase
{
    private string $tmpBase;

    protected function setUp(): void
    {
        $this->tmpBase = sys_get_temp_dir() . '/make_strat_test_' . uniqid();
        mkdir($this->tmpBase, 0755, true);
    }

    protected function tearDown(): void
    {
        // 清理临时目录
        $this->rmrf($this->tmpBase);

        // 重置单例避免 argv 污染
        foreach ([CommandManager::class, CommandRunner::class] as $cls) {
            $reflection = new \ReflectionClass($cls);
            if ($reflection->hasProperty('instance')) {
                $prop = $reflection->getProperty('instance');
                $prop->setAccessible(true);
                $prop->setValue(null, null);
            }
        }
        parent::tearDown();
    }

    private function rmrf(string $dir): void
    {
        if (!is_dir($dir)) {
            return;
        }
        foreach (glob($dir . '/*') as $f) {
            is_dir($f) ? $this->rmrf($f) : unlink($f);
        }
        rmdir($dir);
    }

    /** 用给定选项执行命令，argv 模拟 CLI 入口 */
    private function exec(array $options): string
    {
        $argv = array_merge(['php', 'sikelan', 'trader:make-strategy'], $options);
        CommandManager::getInstance()->setOriginArgv($argv);
        return (string) (new TraderMakeStrategyCommand())->exec([]);
    }

    private function callProtected(string $method, array $args)
    {
        $m = new \ReflectionMethod(TraderMakeStrategyCommand::class, $method);
        $m->setAccessible(true);
        return $m->invokeArgs(new TraderMakeStrategyCommand(), $args);
    }

    /** 把真实 config/trader.php 复制到临时目录，返回临时路径 */
    private function copyConfig(): string
    {
        $src = CONFIG_PATH . '/trader.php';
        $dst = $this->tmpBase . '/trader.php';
        copy($src, $dst);
        return $dst;
    }

    // ====================================================================
    //  1. 自动注册 + 元信息
    // ====================================================================

    public function testCommandAutoRegistered(): void
    {
        CommandRunner::getInstance();
        $m = CommandManager::getInstance();
        $this->assertTrue($m->hasCommand('trader:make-strategy'));
        $this->assertInstanceOf(TraderMakeStrategyCommand::class, $m->getCommand('trader:make-strategy'));
    }

    public function testDescAndHelpCoverKeyOptions(): void
    {
        $cmd = new TraderMakeStrategyCommand();
        $this->assertNotEmpty($cmd->desc());
        $help = (string) $cmd->help([]);
        foreach (['--name', '--class', '--dir', '--template', '--params',
                  '--no-register', '--force', '--dry-run', 'ema', 'meanrev', 'blank'] as $k) {
            $this->assertStringContainsString($k, $help);
        }
    }

    // ====================================================================
    //  2. 纯函数测试：类名 / 参数 / 目录 / 命名空间推导
    // ====================================================================

    public function testClassNameAutoGeneratedFromAlias(): void
    {
        $plan = $this->buildPlan(['name' => 'MyStrat']);
        $this->assertSame('MyStrat', $plan['alias']);
        $this->assertSame('MyStratStrategy', $plan['class']);
    }

    public function testClassNameAlreadyEndsWithStrategyNotDoubled(): void
    {
        $plan = $this->buildPlan(['name' => 'FooStrategy']);
        $this->assertSame('FooStrategy', $plan['class']);
    }

    public function testExplicitClassNameWins(): void
    {
        $plan = $this->buildPlan(['name' => 'MyStrat', 'class' => 'CustomName']);
        $this->assertSame('CustomName', $plan['class']);
    }

    public function testParseScalarTypes(): void
    {
        $this->assertSame(20, $this->callProtected('parseScalar', ['20']));
        $this->assertSame(0.003, $this->callProtected('parseScalar', ['0.003']));
        $this->assertSame(-5, $this->callProtected('parseScalar', ['-5']));
        $this->assertSame(-1.5, $this->callProtected('parseScalar', ['-1.5']));
        $this->assertSame('hello', $this->callProtected('parseScalar', ["'hello'"]));
        $this->assertSame('hello', $this->callProtected('parseScalar', ['"hello"']));
        $this->assertSame('abc', $this->callProtected('parseScalar', ['abc']));
    }

    public function testConstructDefaultsPerTemplate(): void
    {
        $ema = $this->buildPlan(['name' => 'E', 'template' => 'ema']);
        $this->assertSame([20, 50, 0.003], $ema['construct']);

        $mr = $this->buildPlan(['name' => 'M', 'template' => 'meanrev']);
        $this->assertSame([20, 2.0, 14, 30.0, 65.0, 0.8], $mr['construct']);

        $blank = $this->buildPlan(['name' => 'B', 'template' => 'blank']);
        $this->assertSame([], $blank['construct']);
    }

    public function testConstructParamsOverride(): void
    {
        $plan = $this->buildPlan(['name' => 'E', 'template' => 'ema', 'params' => '10,20,0.001']);
        $this->assertSame([10, 20, 0.001], $plan['construct']);
    }

    public function testParamCountMismatchWarns(): void
    {
        $plan = $this->buildPlan(['name' => 'E', 'template' => 'ema', 'params' => '10']);
        $this->assertSame([10], $plan['construct']);
        $this->assertNotNull($plan['param_warn']);
        $this->assertStringContainsString('3 个', $plan['param_warn']);
    }

    public function testResolveDirAbsoluteVsRelative(): void
    {
        $abs = $this->callProtected('resolveDir', ['/tmp/foo/bar']);
        $this->assertSame('/tmp/foo/bar', $abs);

        $rel = $this->callProtected('resolveDir', ['app/MyStrats']);
        $this->assertSame(BASE_PATH . '/app/MyStrats', $rel);
    }

    public function testDeriveNamespaceFromAppSubdir(): void
    {
        $ns = $this->callProtected('deriveNamespace', [
            APP_PATH . '/Services/Trader/Strategies',
            APP_PATH,
        ]);
        $this->assertSame('App\\Services\\Trader\\Strategies', $ns);
    }

    // ====================================================================
    //  3. 参数校验错误
    // ====================================================================

    public function testMissingNameErrors(): void
    {
        $out = $this->exec([]);
        $this->assertStringContainsString('[ERROR]', $out);
        $this->assertStringContainsString('--name', $out);
    }

    public function testInvalidAliasErrors(): void
    {
        $out = $this->exec(['--name=Bad Name!']);
        $this->assertStringContainsString('[ERROR]', $out);
        $this->assertStringContainsString('字母、数字', $out);
    }

    public function testInvalidTemplateErrors(): void
    {
        $out = $this->exec(['--name=X', '--template=notexist']);
        $this->assertStringContainsString('[ERROR]', $out);
        $this->assertStringContainsString('不支持的模板', $out);
    }

    public function testInvalidClassNameErrors(): void
    {
        $out = $this->exec(['--name=X', '--class=1Bad']);
        $this->assertStringContainsString('[ERROR]', $out);
        $this->assertStringContainsString('类名不合法', $out);
    }

    // ====================================================================
    //  4. dry-run 不写文件
    // ====================================================================

    public function testDryRunDoesNotWriteFiles(): void
    {
        $out = $this->exec(['--name=DryStrat', '--template=ema', '--dry-run']);
        $this->assertStringContainsString('DRY-RUN', $out);
        $this->assertStringContainsString('DryStratStrategy', $out);
        // 默认目录下不应生成文件
        $this->assertFileDoesNotExist(APP_PATH . '/Services/Trader/Strategies/DryStratStrategy.php');
    }

    // ====================================================================
    //  5. 端到端：生成文件 + 写 config（全部在临时目录）
    // ====================================================================

    public function testEndToEndEmaCreatesFileAndRegistersInConfig(): void
    {
        $cfg = $this->copyConfig();
        $outDir = $this->tmpBase . '/strats';

        $out = $this->exec([
            '--name=E2eStrat',
            '--template=ema',
            '--params=5,10,0.001',
            '--dir=' . $outDir,
            '--config=' . $cfg,
        ]);

        $this->assertStringContainsString('创建成功', $out);
        $file = $outDir . '/E2eStratStrategy.php';
        $this->assertFileExists($file);
        $this->assertStringContainsString('class E2eStratStrategy extends AbstractStrategy', file_get_contents($file));

        // config 注入正确
        $cfgContent = file_get_contents($cfg);
        $this->assertStringContainsString("'E2eStrat' =>", $cfgContent);
        $this->assertStringContainsString('E2eStratStrategy::class', $cfgContent);
        $this->assertStringContainsString('[5, 10, 0.001]', $cfgContent);

        // 生成的类必须能通过 php -l
        exec('php -l ' . escapeshellarg($file) . ' 2>&1', $lines, $code);
        $this->assertSame(0, $code, '生成的策略类必须语法正确：' . implode('', $lines));

        // 修改后的 config 必须仍是合法 PHP
        $this->assertSame(0, $this->phpLintCode($cfg), '修改后的 config/trader.php 必须语法正确');
    }

    public function testEndToEndBlankTemplateUsesSimplifiedConfigEntry(): void
    {
        $cfg = $this->copyConfig();
        $outDir = $this->tmpBase . '/strats';

        $this->exec([
            '--name=Blank2',
            '--template=blank',
            '--dir=' . $outDir,
            '--config=' . $cfg,
        ]);

        $cfgContent = file_get_contents($cfg);
        // blank 模板无构造参数 → 简写形式 'alias' => \Class::class
        $this->assertStringContainsString(
            "'Blank2' => \App\Services\Trader\Strategies\Blank2Strategy::class",
            $cfgContent
        );
        $this->assertStringNotContainsString("'Blank2' => [", $cfgContent);
        $this->assertSame(0, $this->phpLintCode($cfg));
    }

    public function testNoRegisterSkipsConfig(): void
    {
        $cfg = $this->copyConfig();
        $outDir = $this->tmpBase . '/strats';

        $this->exec([
            '--name=NoReg',
            '--template=blank',
            '--dir=' . $outDir,
            '--config=' . $cfg,
            '--no-register',
        ]);

        $this->assertFileExists($outDir . '/NoRegStrategy.php');
        $this->assertStringNotContainsString('NoReg', file_get_contents($cfg));
    }

    public function testExistingFileWithoutForceWarns(): void
    {
        $cfg = $this->copyConfig();
        $outDir = $this->tmpBase . '/strats';
        mkdir($outDir, 0755, true);
        file_put_contents($outDir . '/ExistStrategy.php', '<?php // old');

        $out = $this->exec([
            '--name=Exist',
            '--template=blank',
            '--dir=' . $outDir,
            '--config=' . $cfg,
        ]);

        $this->assertStringContainsString('[WARN]', $out);
        $this->assertStringContainsString('已存在', $out);
        // 原文件未被覆盖
        $this->assertStringContainsString('// old', file_get_contents($outDir . '/ExistStrategy.php'));
        // config 未被修改
        $this->assertStringNotContainsString('Exist', file_get_contents($cfg));
    }

    public function testForceOverwritesExistingFile(): void
    {
        $cfg = $this->copyConfig();
        $outDir = $this->tmpBase . '/strats';
        mkdir($outDir, 0755, true);
        file_put_contents($outDir . '/ForceStrategy.php', '<?php // old');

        $this->exec([
            '--name=Force',
            '--template=blank',
            '--dir=' . $outDir,
            '--config=' . $cfg,
            '--force',
        ]);

        // 文件被覆盖为新模板内容
        $this->assertStringContainsString(
            'class ForceStrategy extends AbstractStrategy',
            file_get_contents($outDir . '/ForceStrategy.php')
        );
    }

    public function testDuplicateAliasInConfigRejected(): void
    {
        $cfg = $this->copyConfig();
        $outDir = $this->tmpBase . '/strats';

        // 第一次创建成功
        $this->exec([
            '--name=Dup',
            '--template=blank',
            '--dir=' . $outDir,
            '--config=' . $cfg,
        ]);

        // 第二次：别名已在 config，但用 --class 换一个类名（类文件不存在）→ 应被 config 级检查拦截
        $out = $this->exec([
            '--name=Dup',
            '--class=OtherStrategy',
            '--template=blank',
            '--dir=' . $outDir . '/sub',
            '--config=' . $cfg,
        ]);

        $this->assertStringContainsString('[ERROR]', $out);
        $this->assertStringContainsString('已存在于 config', $out);
    }

    public function testGeneratedStrategyImplementsInterface(): void
    {
        // 生成后通过反射确认它实现 StrategyInterface
        $cfg = $this->copyConfig();
        $outDir = $this->tmpBase . '/strats';

        $this->exec([
            '--name=Iface',
            '--template=ema',
            '--dir=' . $outDir,
            '--config=' . $cfg,
            '--no-register',
        ]);

        require $outDir . '/IfaceStrategy.php';
        $rc = new \ReflectionClass('\\App\\Services\\Trader\\Strategies\\IfaceStrategy');
        $this->assertTrue(
            $rc->implementsInterface(\App\Services\Trader\Strategy\StrategyInterface::class),
            '生成的策略必须实现 StrategyInterface'
        );
        $this->assertTrue($rc->isInstantiable(), '策略类必须可实例化');
    }

    // ====================================================================
    //  helpers
    // ====================================================================

    /** 用最简 raw 选项调 buildPlan（name 必填，其余默认） */
    private function buildPlan(array $over): array
    {
        $defaults = [
            'name'        => 'X',
            'class'       => '',
            'dir'         => '',
            'namespace'   => '',
            'template'    => 'ema',
            'params'      => '',
            'no_register' => false,
            'force'       => false,
            'dry_run'     => false,
            'config_path' => CONFIG_PATH . '/trader.php',
        ];
        [$plan, $err] = $this->callProtected('buildPlan', [array_merge($defaults, $over)]);
        $this->assertNull($err, 'buildPlan 不应出错：' . ($err ?? ''));
        return $plan;
    }

    private function phpLintCode(string $file): int
    {
        exec('php -l ' . escapeshellarg($file) . ' 2>&1', $lines, $code);
        return (int) $code;
    }
}
